// Seed data for Chloe's trip — The South of France, May 2026
// This is used both for DB seeding and for demo mode (no Supabase)

import type { Trip, Guest, TripDay, Event, EventAlternative } from './types'

export const DEMO_TRIP_ID = 'demo'

export const SEED_TRIP: Omit<Trip, 'host_id' | 'created_at'> = {
  id: DEMO_TRIP_ID,
  title: 'The South of France',
  subtitle: 'May 2026',
  destination: 'Côte d\'Azur',
  start_date: '2026-05-12',
  end_date: '2026-05-17',
  tone: 'effortless',
  status: 'active',
}

export const SEED_GUESTS: Omit<Guest, 'created_at'>[] = [
  { id: 'g-chloe', trip_id: DEMO_TRIP_ID, name: 'Chloe', initial: 'C', city: 'Hong Kong', phone: '+852XXXXXXXX', email: null, token: 'chloe-host', responded: true },
  { id: 'g-sophia', trip_id: DEMO_TRIP_ID, name: 'Sophia', initial: 'S', city: 'Los Angeles', phone: '+1XXXXXXXXXX', email: null, token: 'sophia-invite', responded: false },
  { id: 'g-aria', trip_id: DEMO_TRIP_ID, name: 'Aria', initial: 'A', city: 'Singapore', phone: '+65XXXXXXXX', email: null, token: 'aria-invite', responded: false },
  { id: 'g-noor', trip_id: DEMO_TRIP_ID, name: 'Noor', initial: 'N', city: 'Dubai', phone: '+971XXXXXXXX', email: null, token: 'noor-invite', responded: false },
]

export const SEED_DAYS: Omit<TripDay, 'id'>[] = [
  { trip_id: DEMO_TRIP_ID, day_number: 1, title: 'Arrival', theme: 'SETTLE IN', sort_order: 1 },
  { trip_id: DEMO_TRIP_ID, day_number: 2, title: 'The Coast', theme: 'SUN & SEA', sort_order: 2 },
  { trip_id: DEMO_TRIP_ID, day_number: 3, title: 'Into the Hills', theme: 'EXPLORE', sort_order: 3 },
  { trip_id: DEMO_TRIP_ID, day_number: 4, title: 'La Dolce Vita', theme: 'INDULGE', sort_order: 4 },
  { trip_id: DEMO_TRIP_ID, day_number: 5, title: 'The Last Morning', theme: 'DEPARTURE', sort_order: 5 },
]

// Events keyed by day index (0-based)
export const SEED_EVENTS: Record<number, Omit<Event, 'id' | 'trip_day_id'>[]> = {
  0: [
    {
      trip_id: DEMO_TRIP_ID,
      time: '16h',
      title: 'Villa Les Oliviers',
      subtitle: 'Champagne is poured before luggage is unpacked',
      detail: 'A stone villa above the Baie des Canebiers, ten minutes from Saint-Tropez but a world away from the circus. Four bedrooms, each with its own terrace. A pool that catches the last light. The kind of place where you hear nothing but cicadas and the occasional clink of a glass being refilled.',
      dress_code: 'Travel \u2014 linen, silk, something you felt good boarding in',
      event_type: 'arrival',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 1,
    },
    {
      trip_id: DEMO_TRIP_ID,
      time: '20h30',
      title: 'Dinner on the Terrace',
      subtitle: 'A private chef. The best of the morning market.',
      detail: 'Chef Mathilde arrives at six with crates from the march\u00e9 proven\u00e7al. You don\'t need to think about a thing. Socca to start, whole grilled loup de mer with herbs from the garden, a salade ni\u00e7oise that will ruin all future salade ni\u00e7oises, and a tarte aux figues that someone will try to get the recipe for. Wine from Domaine Ott. The table is set under the olive trees. Candles lit as the sun drops.',
      dress_code: 'First night ease \u2014 a beautiful caftan, bare feet, gold at the ears',
      event_type: 'dinner',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 2,
    },
  ],
  1: [
    {
      trip_id: DEMO_TRIP_ID,
      time: '9h',
      title: 'Morning by the Pool',
      subtitle: 'Coffee, fruit, croissants from the village. No alarms.',
      detail: 'Breakfast is laid out by the pool from eight. Fresh-squeezed orange juice, pain au chocolat still warm from the boulangerie in Ramatuelle, Greek yogurt with Proven\u00e7al honey, a fruit plate that looks like a still life. Take your time. Read. Float. There is nowhere to be until lunch.',
      dress_code: null,
      event_type: 'morning',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 1,
    },
    {
      trip_id: DEMO_TRIP_ID,
      time: '12h30',
      title: 'Club 55',
      subtitle: 'The most beautiful hidden beach on the Riviera. No scene. Just the sea.',
      detail: 'Pampelonne Beach, but the quiet end. Club 55 has been here since Brigitte Bardot made Saint-Tropez famous, and it still feels like a secret. Grilled fish, ros\u00e9 from the ice bucket, sand between your toes, the Mediterranean doing what it does. This is the afternoon that everyone will photograph and no filter will improve.',
      dress_code: 'Beach to lunch \u2014 swimwear with something beautiful over it. A pareu, a linen shirt, those sandals',
      event_type: 'lunch',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 2,
    },
    {
      trip_id: DEMO_TRIP_ID,
      time: '16h',
      title: 'Spa at Villa',
      subtitle: 'Two masseuses arrive. Lavender oil, warm stones, silence.',
      detail: 'Back at the villa by four. Two therapists from Bastide de la Mer set up by the pool. Deep tissue or relaxation \u2014 your choice. Cucumber water, chilled towels, the sound of nothing. This is the kind of afternoon that recalibrates everything.',
      dress_code: null,
      event_type: 'spa',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 3,
    },
    {
      trip_id: DEMO_TRIP_ID,
      time: '20h',
      title: 'La Vague d\'Or',
      subtitle: 'Three Michelin stars. Arnaud Donckele\'s cathedral of taste.',
      detail: 'At the Ch\u00e2teau de la Messardi\u00e8re, overlooking the bay. This is not dinner \u2014 this is theater. A twelve-course tasting menu that tells the story of Provence through the lens of one of the world\'s greatest chefs. Each course arrives like a small revelation. The wine pairing is extraordinary. Dress for the occasion \u2014 this is the night.',
      dress_code: 'The dress you brought for this. Heels that work on stone. The jewellery you almost left at home but didn\'t.',
      event_type: 'dinner',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 4,
    },
  ],
  2: [
    {
      trip_id: DEMO_TRIP_ID,
      time: '9h30',
      title: 'Market Morning in Ramatuelle',
      subtitle: 'Lavender, fresh cheese, vintage linen \u2014 bring an empty tote',
      detail: 'Thursday is market day. The village square fills with stalls selling saucisson, ch\u00e8vre so fresh it\'s still warm, olive oil pressed that morning, bundles of dried lavender, hand-thrown ceramics, vintage proven\u00e7al textiles. This is where you find the gifts you\'ll actually keep. Coffee at the caf\u00e9 on the corner, watching the village wake up.',
      dress_code: 'Morning market \u2014 cotton dress, flat sandals, a hat. Easy beauty.',
      event_type: 'explore',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 1,
    },
    {
      trip_id: DEMO_TRIP_ID,
      time: '12h',
      title: 'Lunch at Chez Bruno',
      subtitle: 'The truffle king of Provence, in the hills above Lorgues',
      detail: 'An hour into the Var countryside to a restaurant that has served nothing but truffles for forty years. Black truffle omelette, truffle risotto, truffle ice cream \u2014 and somehow none of it feels excessive. The dining room opens onto a garden. Bruno himself may appear. Bring cash for the truffle shop on the way out.',
      dress_code: null,
      event_type: 'lunch',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 2,
    },
    {
      trip_id: DEMO_TRIP_ID,
      time: '15h30',
      title: 'Wine Tasting at Ch\u00e2teau Minuty',
      subtitle: 'The ros\u00e9 you\'ve been drinking all week, at the source',
      detail: 'Thirty minutes through the Massif des Maures to one of the oldest estates in Provence. A private tasting in the chai \u2014 four ros\u00e9s, a rare white, and the prestige cuv\u00e9e that doesn\'t leave the property. The vineyard manager tells stories you won\'t find on the website. Order cases to be shipped home.',
      dress_code: null,
      event_type: 'activity',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 3,
    },
    {
      trip_id: DEMO_TRIP_ID,
      time: '20h30',
      title: 'Dinner at the Villa',
      subtitle: 'We cook tonight. Together. Badly, beautifully.',
      detail: 'Everything we bought at the market this morning, plus whatever Chef Mathilde prepped before she left. This is the messy, loud, wine-fuelled dinner where someone burns the garlic and nobody cares. Pasta made by hand (poorly), the good cheese on a board, too much bread. Music on the speakers, dancing in the kitchen, the kind of night that becomes the story you tell about this trip.',
      dress_code: 'Bare feet. The shirt you don\'t mind staining. Hair up.',
      event_type: 'dinner',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 4,
    },
  ],
  3: [
    {
      trip_id: DEMO_TRIP_ID,
      time: '10h',
      title: 'Boat Day',
      subtitle: 'A vintage Riva picks you up from the dock at Sainte-Maxime',
      detail: 'A mahogany Riva Aquarama, captain included. Cruising the coast from Sainte-Maxime to the \u00celes de Porquerolles \u2014 the most beautiful island in the Mediterranean that most people have never heard of. Swimming stops in turquoise calanques. Lunch on board: cold lobster, Sancerre on ice, peaches. The captain knows every hidden cove. This is the day the trip peaks.',
      dress_code: 'Boat day \u2014 swimsuit, cover-up, SPF 50. Sunglasses that stay on your face in the wind.',
      event_type: 'activity',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 1,
    },
    {
      trip_id: DEMO_TRIP_ID,
      time: '16h',
      title: 'Free Afternoon',
      subtitle: 'Time apart before the final evening. Space to miss each other before saying goodbye.',
      detail: 'Back at the villa by four. Some will nap. Some will swim. Someone will find a spot in the garden with a book and not move for two hours. The villa has a small library of French novels and coffee table books about Proven\u00e7al architecture. There\'s a hammock between the olive trees that nobody has claimed yet.',
      dress_code: null,
      event_type: 'free',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 2,
    },
    {
      trip_id: DEMO_TRIP_ID,
      time: '19h30',
      title: 'Drinks at H\u00f4tel de Paris',
      subtitle: 'Rooftop terrace. The golden hour hits different here.',
      detail: 'Aperitifs on the rooftop of the H\u00f4tel de Paris in Saint-Tropez. Negronis, Champagne, whatever calls. The light at this hour turns the harbour gold. The boats below are absurd. The people-watching is extraordinary. One hour, two drinks, then dinner.',
      dress_code: 'Aperitif hour \u2014 elevated casual. The kind of outfit that looks effortless but wasn\'t.',
      event_type: 'drinks',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 3,
    },
    {
      trip_id: DEMO_TRIP_ID,
      time: '21h',
      title: 'The Final Dinner',
      subtitle: 'L\'Auberge des Maures. Old Saint-Tropez. No tourists.',
      detail: 'A tiny restaurant on a cobblestone street in the old town, far from the port and the noise. Family-run for three generations. The grandmother still makes the ratatouille. A prix fixe menu that changes with what the fishermen brought in. The wine list is short and every bottle is perfect. This is the dinner where someone cries \u2014 not because it\'s sad, but because it was all so beautiful and it\'s almost over.',
      dress_code: 'Last night \u2014 your favourite thing. The piece you\'ll remember wearing on this trip.',
      event_type: 'dinner',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 4,
    },
  ],
  4: [
    {
      trip_id: DEMO_TRIP_ID,
      time: '9h',
      title: 'Last Breakfast',
      subtitle: 'One more morning in paradise. Slow coffee. Long hugs.',
      detail: 'The final breakfast by the pool. Everything laid out one last time. Someone suggests a photo and for once everyone agrees. The light is perfect. The croissants are perfect. The company was perfect. Pack slowly. Trade flight details. Make impossible promises about doing this every year.',
      dress_code: 'Travel \u2014 comfort meets style. The airport outfit that still looks good at arrivals.',
      event_type: 'morning',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 1,
    },
    {
      trip_id: DEMO_TRIP_ID,
      time: '12h',
      title: 'Departures',
      subtitle: 'Nice airport \u2014 90 minutes. Or stay forever.',
      detail: 'Transfers arranged to Nice C\u00f4te d\'Azur. Sophia and Noor fly early afternoon. Aria has an evening flight \u2014 time for one last solo wander through Nice\'s old town. Chloe stays an extra night at the villa because some things are hard to leave.',
      dress_code: null,
      event_type: 'transit',
      locked: false,
      booking_status: null,
      booking_ref: null,
      sort_order: 2,
    },
  ],
}

export const SEED_ALTERNATIVES: Record<string, Omit<EventAlternative, 'id' | 'event_id'>[]> = {
  // Alternatives for Club 55 (day 2, event 2)
  'day-1-event-1': [
    { title: 'Nikki Beach', detail: 'More scene, more music, more champagne spray. If the group wants energy over serenity.', sort_order: 1 },
    { title: 'Plage de l\'Escalet', detail: 'Wild beach, no restaurant, bring a picnic. For the group that wants privacy above all.', sort_order: 2 },
  ],
  // Alternatives for La Vague d'Or (day 2, event 4)
  'day-1-event-3': [
    { title: 'Le Mas de Chastelas', detail: 'Beautiful but less formal. Garden dining, Proven\u00e7al menu, easier to get in.', sort_order: 1 },
  ],
  // Alternatives for Boat Day (day 4, event 1)
  'day-3-event-0': [
    { title: 'Catamaran Charter', detail: 'Larger vessel, more space, but less romantic than the Riva.', sort_order: 1 },
    { title: 'Porquerolles by Ferry + Bikes', detail: 'Take the public ferry from Hy\u00e8res, rent bikes on the island. More adventurous, less luxury.', sort_order: 2 },
  ],
}
